[package]
name = "gitmereba"
description = "Clon local y operativo de cuentas de GitHub sobre Gitea"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", default-features = false, features = ["config-json"] }

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
gitmereba-core = { path = "../crates/core" }
rpassword = "7.5.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2.11.6", default-features = false, features = ["wry", "compression", "x11", "dbus"] }
tauri-plugin-dialog = { version = "2.7.3", default-features = false, features = ["xdg-portal"] }
time = { version = "0.3.55", features = ["formatting", "local-offset"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "signal", "sync"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["fmt", "env-filter", "ansi"] }

[dev-dependencies]
tempfile = "3.27.0"
